import { useId, type CSSProperties } from 'react';
import s from './DeucepointMark.module.css';

/**
 * Deucepoint mark — a black-and-white tennis ball on fire.
 *
 * direction='up' is the upright mark; 'left' / 'right' is the comet: fire trailing off that side
 * of the ball (so 'left' = ball flying to the right). `size` is always the rendered HEIGHT.
 *
 * Colour follows CSS `color` (ink) and `--dp-paper` (the page background, default #F6F6F2),
 * so on a dark surface set `style={{ color: '#F6F6F2', '--dp-paper': '#14161A' }}`.
 * Motion is pure CSS; it respects prefers-reduced-motion.
 */
export type DeucepointMarkProps = {
  /** Rendered height in px (or any CSS length); width follows the aspect ratio. Default 40. */
  size?: number | string;
  /** 'up' (default): flames rise from the ball. 'left' / 'right': flames trail off that side. */
  direction?: 'up' | 'left' | 'right';
  /** 'mono' keeps the flame in ink; 'flame' colours it orange/amber. */
  variant?: 'mono' | 'flame';
  /** 'ink' (default) or 'optic' — the tennis-ball yellow (#DFFF4F). Or set --dp-ball yourself. */
  ball?: 'ink' | 'optic';
  /** false renders just the ball (square, tight). With `ignite` it drops in and bounces instead of igniting. */
  flames?: boolean;
  /** Idle flicker + rising embers. Default true. */
  animated?: boolean;
  /** Play the ignition (ball pops, fire grows) on mount. Default false. */
  ignite?: boolean;
  /** Ball spin: on hover (default), always, or never. */
  spin?: 'hover' | 'always' | 'never';
  /** Force the hover "hot" stretch (e.g. while a simulation runs). */
  hot?: boolean;
  /** Accessible name. Pass '' to hide from assistive tech when next to visible text. */
  title?: string;
  className?: string;
  style?: CSSProperties;
};

// Generated by tools/build.js — geometry lives there.
const GEO = {
  up: {
    viewBox: '4.88 -2 96 96', aspect: 1,
    cx: 50, cy: 68,
    outer: 'M33 70 C23 58 24 42 32 30 C30 24 30 18 33 14 C37 20 39 26 43 30 C42 20 48 12 58 5 C57 12 60 16 64 18 C70 20 74 26 73 34 C76 32 78 28 77 24 C83 38 80 58 68 70 Z',
    inner: 'M41 70 C36 58 40 46 50 32 C53 28 57 26 58 20 C61 30 63 44 62 56 C62 62 61 66 59 70 Z',
    seam: 'M72.0 68.6L72.0 68.3L71.9 67.9L71.9 67.6L71.8 67.2L71.6 66.7L71.5 66.3L71.3 65.8L71.1 65.2L70.9 64.7L70.6 64.1L70.4 63.5L70.1 62.9L69.7 62.3L69.4 61.6L69.0 61.0L68.6 60.3L68.2 59.6L67.8 58.9L67.3 58.2L66.9 57.5L66.4 56.8L65.9 56.1L65.4 55.4L64.8 54.7L64.3 54.0L63.7 53.4L63.1 52.7L62.5 52.1L61.9 51.5L61.3 50.9L60.6 50.4L60.0 49.8L59.3 49.3L58.6 48.9L57.9 48.4L57.2 48.0L56.5 47.7L55.8 47.3L55.0 47.0L54.3 46.8L53.5 46.6L52.7 46.4L52.0 46.2L51.2 46.1L50.4 46.1L49.6 46.0L48.8 46.0L48.0 46.1 M32.0 55.4L31.6 55.9L31.3 56.5L31.0 57.0L30.8 57.6L30.5 58.1L30.4 58.7L30.3 59.2L30.2 59.7L30.1 60.2L30.2 60.7L30.2 61.2L30.3 61.7L30.4 62.2L30.6 62.7L30.8 63.2L31.1 63.6L31.4 64.1L31.8 64.5L32.2 65.0L32.6 65.4L33.1 65.9L33.6 66.3L34.1 66.7L34.6 67.2L35.2 67.6L35.9 68.0L36.5 68.4L37.2 68.8L37.9 69.3L38.6 69.7L39.3 70.1L40.0 70.6L40.8 71.0L41.5 71.5L42.3 71.9L43.0 72.4L43.8 72.8L44.5 73.3L45.3 73.8L46.0 74.3L46.7 74.8L47.4 75.3L48.1 75.8L48.8 76.3L49.4 76.8L50.0 77.3L50.6 77.9L51.2 78.4L51.7 79.0L52.2 79.5L52.6 80.1L53.0 80.6L53.4 81.2L53.7 81.7L54.0 82.3L54.2 82.8L54.4 83.3L54.6 83.8L54.7 84.4L54.7 84.9L54.7 85.4L54.7 85.8L54.6 86.3L54.5 86.7L54.4 87.1L54.2 87.5L53.9 87.9L53.6 88.3L53.3 88.6L52.9 88.9L52.5 89.1L52.1 89.3L51.7 89.5L51.2 89.7L50.7 89.8L50.1 89.9L49.6 90.0L49.0 90.0',
    embers: [[33, 12, 1.6, '-3px', '2.6s', '0s'], [58, 3, 2.2, '2px', '2.9s', '-1.1s'], [77, 22, 1.4, '3px', '2.3s', '-0.5s'], [47, 15, 1.8, '-1px', '2.5s', '-1.8s'], [67, 9, 1.5, '1px', '2.1s', '-0.3s']],
  },
  left: {
    viewBox: '4.2 23.6 148.8 51.4', aspect: 2.8949,
    cx: 118, cy: 50,
    wrapper: 'translate(118 50) rotate(-90) translate(-50 -68)',
    outer: 'M36.74 71.2 C28.94 52 29.72 26.4 35.96 7.2 C34.4 -2.4 34.4 -12 36.74 -18.4 C39.86 -8.8 41.42 0.8 44.54 7.2 C43.76 -8.8 48.44 -21.6 56.24 -32.8 C55.46 -21.6 57.8 -15.2 60.92 -12 C65.6 -8.8 68.72 0.8 67.94 13.6 C70.28 10.4 71.84 4 71.06 -2.4 C75.74 20 73.4 52 64.04 71.2 Z',
    inner: 'M42.62 70.5 C38.52 55.5 41.8 40.5 50 23 C52.46 18 55.74 15.5 56.56 8 C59.02 20.5 60.66 38 59.84 53 C59.84 60.5 59.02 65.5 57.38 70.5 Z',
    seam: 'M140.0 50.6L140.0 50.3L139.9 49.9L139.9 49.6L139.8 49.2L139.6 48.7L139.5 48.3L139.3 47.8L139.1 47.2L138.9 46.7L138.6 46.1L138.4 45.5L138.1 44.9L137.7 44.3L137.4 43.6L137.0 43.0L136.6 42.3L136.2 41.6L135.8 40.9L135.3 40.2L134.9 39.5L134.4 38.8L133.9 38.1L133.4 37.4L132.8 36.7L132.3 36.0L131.7 35.4L131.1 34.7L130.5 34.1L129.9 33.5L129.3 32.9L128.6 32.4L128.0 31.8L127.3 31.3L126.6 30.9L125.9 30.4L125.2 30.0L124.5 29.7L123.8 29.3L123.0 29.0L122.3 28.8L121.5 28.6L120.7 28.4L120.0 28.2L119.2 28.1L118.4 28.1L117.6 28.0L116.8 28.0L116.0 28.1 M100.0 37.4L99.6 37.9L99.3 38.5L99.0 39.0L98.8 39.6L98.5 40.1L98.4 40.7L98.3 41.2L98.2 41.7L98.1 42.2L98.2 42.7L98.2 43.2L98.3 43.7L98.4 44.2L98.6 44.7L98.8 45.2L99.1 45.6L99.4 46.1L99.8 46.5L100.2 47.0L100.6 47.4L101.1 47.9L101.6 48.3L102.1 48.7L102.6 49.2L103.2 49.6L103.9 50.0L104.5 50.4L105.2 50.8L105.9 51.3L106.6 51.7L107.3 52.1L108.0 52.6L108.8 53.0L109.5 53.5L110.3 53.9L111.0 54.4L111.8 54.8L112.5 55.3L113.3 55.8L114.0 56.3L114.7 56.8L115.4 57.3L116.1 57.8L116.8 58.3L117.4 58.8L118.0 59.3L118.6 59.9L119.2 60.4L119.7 61.0L120.2 61.5L120.6 62.1L121.0 62.6L121.4 63.2L121.7 63.7L122.0 64.3L122.2 64.8L122.4 65.3L122.6 65.8L122.7 66.4L122.7 66.9L122.7 67.4L122.7 67.8L122.6 68.3L122.5 68.7L122.4 69.1L122.2 69.5L121.9 69.9L121.6 70.3L121.3 70.6L120.9 70.9L120.5 71.1L120.1 71.3L119.7 71.5L119.2 71.7L118.7 71.8L118.1 71.9L117.6 72.0L117.0 72.0',
    embers: [[36.7, -21.6, 1.6, '-3px', '2.6s', '0s'], [56.2, -36, 2.2, '2px', '2.9s', '-1.1s'], [71.1, -5.6, 1.4, '3px', '2.3s', '-0.5s'], [47.7, -16.8, 1.8, '-1px', '2.5s', '-1.8s'], [63.3, -26.4, 1.5, '1px', '2.1s', '-0.3s']],
  },
  right: {
    viewBox: '7 23.6 148.8 51.4', aspect: 2.8949,
    cx: 42, cy: 50,
    wrapper: 'translate(42 50) scale(-1 1) rotate(-90) translate(-50 -68)',
    outer: 'M36.74 71.2 C28.94 52 29.72 26.4 35.96 7.2 C34.4 -2.4 34.4 -12 36.74 -18.4 C39.86 -8.8 41.42 0.8 44.54 7.2 C43.76 -8.8 48.44 -21.6 56.24 -32.8 C55.46 -21.6 57.8 -15.2 60.92 -12 C65.6 -8.8 68.72 0.8 67.94 13.6 C70.28 10.4 71.84 4 71.06 -2.4 C75.74 20 73.4 52 64.04 71.2 Z',
    inner: 'M42.62 70.5 C38.52 55.5 41.8 40.5 50 23 C52.46 18 55.74 15.5 56.56 8 C59.02 20.5 60.66 38 59.84 53 C59.84 60.5 59.02 65.5 57.38 70.5 Z',
    seam: 'M20.0 50.6L20.0 50.3L20.1 49.9L20.1 49.6L20.2 49.2L20.4 48.7L20.5 48.3L20.7 47.8L20.9 47.2L21.1 46.7L21.4 46.1L21.6 45.5L21.9 44.9L22.3 44.3L22.6 43.6L23.0 43.0L23.4 42.3L23.8 41.6L24.2 40.9L24.7 40.2L25.1 39.5L25.6 38.8L26.1 38.1L26.6 37.4L27.2 36.7L27.7 36.0L28.3 35.4L28.9 34.7L29.5 34.1L30.1 33.5L30.7 32.9L31.4 32.4L32.0 31.8L32.7 31.3L33.4 30.9L34.1 30.4L34.8 30.0L35.5 29.7L36.2 29.3L37.0 29.0L37.7 28.8L38.5 28.6L39.3 28.4L40.0 28.2L40.8 28.1L41.6 28.1L42.4 28.0L43.2 28.0L44.0 28.1 M60.0 37.4L60.4 37.9L60.7 38.5L61.0 39.0L61.2 39.6L61.5 40.1L61.6 40.7L61.7 41.2L61.8 41.7L61.9 42.2L61.8 42.7L61.8 43.2L61.7 43.7L61.6 44.2L61.4 44.7L61.2 45.2L60.9 45.6L60.6 46.1L60.2 46.5L59.8 47.0L59.4 47.4L58.9 47.9L58.4 48.3L57.9 48.7L57.4 49.2L56.8 49.6L56.1 50.0L55.5 50.4L54.8 50.8L54.1 51.3L53.4 51.7L52.7 52.1L52.0 52.6L51.2 53.0L50.5 53.5L49.7 53.9L49.0 54.4L48.2 54.8L47.5 55.3L46.7 55.8L46.0 56.3L45.3 56.8L44.6 57.3L43.9 57.8L43.2 58.3L42.6 58.8L42.0 59.3L41.4 59.9L40.8 60.4L40.3 61.0L39.8 61.5L39.4 62.1L39.0 62.6L38.6 63.2L38.3 63.7L38.0 64.3L37.8 64.8L37.6 65.3L37.4 65.8L37.3 66.4L37.3 66.9L37.3 67.4L37.3 67.8L37.4 68.3L37.5 68.7L37.6 69.1L37.8 69.5L38.1 69.9L38.4 70.3L38.7 70.6L39.1 70.9L39.5 71.1L39.9 71.3L40.3 71.5L40.8 71.7L41.3 71.8L41.9 71.9L42.4 72.0L43.0 72.0',
    embers: [[36.7, -21.6, 1.6, '-3px', '2.6s', '0s'], [56.2, -36, 2.2, '2px', '2.9s', '-1.1s'], [71.1, -5.6, 1.4, '3px', '2.3s', '-0.5s'], [47.7, -16.8, 1.8, '-1px', '2.5s', '-1.8s'], [63.3, -26.4, 1.5, '1px', '2.1s', '-0.3s']],
  },
} as const;
const BARE_VIEWBOX = '27 45 46 46';
const R = 22, GAP = 3.5, SEAM_W = 5, SOFT = 2;

export function DeucepointMark({
  size = 40,
  direction = 'up',
  variant = 'mono',
  ball = 'ink',
  flames = true,
  animated = true,
  ignite = false,
  spin = 'hover',
  hot = false,
  title = 'Deucepoint',
  className,
  style,
}: DeucepointMarkProps) {
  const id = useId().replace(/[^a-zA-Z0-9_-]/g, ''); // useId() wraps in ':' or '«»' depending on React version
  const clipId = `dp-knockout-${id}`;
  const ballClipId = `dp-ball-${id}`;
  const g = GEO[flames ? direction : 'up'];
  const classes = [
    s.mark,
    variant === 'flame' && s.isFlame,
    ball === 'optic' && s.isOptic,
    !flames && s.isBare,
    animated && ignite && s.isIgnite,
    animated && spin === 'always' && s.isSpinning,
    animated && hot && s.isHot,
    !animated && s.isStatic,
    className,
  ].filter(Boolean).join(' ');
  const aspect = flames ? g.aspect : 1;
  const width = typeof size === 'number' ? Math.round(size * aspect) : undefined; // string sizes: width is auto from the viewBox

  return (
    <svg
      className={classes}
      style={style}
      viewBox={flames ? g.viewBox : BARE_VIEWBOX}
      width={width}
      height={size}
      role={title ? 'img' : undefined}
      aria-label={title || undefined}
      aria-hidden={title ? undefined : true}
      data-spin={spin}
    >
      <defs>
        <clipPath id={clipId}>
          <path
            clipRule="evenodd"
            d={`M-300 -300H500V500H-300Z M${g.cx - R - GAP} ${g.cy} a${R + GAP} ${R + GAP} 0 1 0 ${2 * (R + GAP)} 0 a${R + GAP} ${R + GAP} 0 1 0 ${-2 * (R + GAP)} 0Z`}
          />
        </clipPath>
        <clipPath id={ballClipId}><circle cx={g.cx} cy={g.cy} r={R} /></clipPath>
      </defs>
      {flames && (
        <g clipPath={`url(#${clipId})`}>
          <g transform={'wrapper' in g ? g.wrapper : undefined}>
            <g className={s.fire}>
              <g className={s.flames}>
                <path className={s.flameOuter} style={{ strokeWidth: SOFT }} d={g.outer} />
                <path className={s.flameInner} d={g.inner} />
              </g>
              {animated && (
                <g>
                  {g.embers.map(([cx, cy, er, dx, dur, delay], i) => (
                    <circle key={i} className={s.ember} cx={cx} cy={cy} r={er} style={{ '--dx': dx, '--dur': dur, '--delay': delay } as CSSProperties} />
                  ))}
                </g>
              )}
            </g>
          </g>
        </g>
      )}
      <g className={s.drop}>
        <g className={s.ball}>
          <circle className={s.ballFill} cx={g.cx} cy={g.cy} r={R} />
          <g clipPath={`url(#${ballClipId})`}>
            <path className={s.seam} style={{ strokeWidth: SEAM_W }} d={g.seam} />
          </g>
        </g>
      </g>
    </svg>
  );
}

export default DeucepointMark;
